[project]
name = "music"
version = "0.1.0"
description = "Add a short description here"
authors = ["Sergey Mikhno <sergey.mikhno@gmail.com>"]
channels = ["conda-forge"]
platforms = ["osx-64"]

[tasks]

[dependencies]
python = "3.10.*"
black = ">=24.4.2,<24.5"
kivy = ">=2.3.0,<2.4"
py2app = ">=0.28.7,<0.29"
setuptools = "69.5.1"
pyinstaller = "5.13.0"
yt-dlp = ">=2024.7.2,<2024.8"

[pypi-dependencies]

pyobjc = "~=10.3.1"
